#!/usr/bin/env Rscript

########################################################################
## Plot PCoA plots and add 95% confidence ellipses in R.               #
## the input pcoa file can be generated by QIIME                       #
##                                                                     #
########################################################################

### 2d plots of PCoA
library(ellipse)
library(car)

setwd("working/directory/01_dust")
input = "pcoa_weighted_unifrac_Guliya.txt"

sample_number = 33

data_pcoa = read.table(input, header = T,
                       sep ="\t",row.names = 1, na.strings = "NA", fill=T)

pcoa1_explain_tem = data_pcoa [sample_number+1,1]; pcoa1_explain = round (pcoa1_explain_tem * 100, digits = 1)
pcoa2_explain_tem = data_pcoa [sample_number+1,2]; pcoa2_explain = round (pcoa2_explain_tem * 100, digits = 1)

data_pcoa = data_pcoa [1:sample_number,]


## plot based on dust high vs low
col_group = "dustT"
filename <- paste(input, "_" , col_group, ".pdf", sep=""); outfile <- paste(getwd(), filename, sep="/")
pdf(file = outfile, width = 4, height = 4)

plot(data_pcoa$pcoa1, data_pcoa$pcoa2, ylim=c(-0.35,0.25), xlim=c(-0.5,0.45), xlab= paste ("PCoA1 (", pcoa1_explain, "%)", sep = ""),
     ylab= paste ("PCoA2 (", pcoa2_explain, "%)", sep = ""), cex.main=0.6, cex.lab=0.6, cex.axis=0.6, cex=1.0,
     pch = ifelse(data_pcoa$dustT == "high", 16, 1), 
     col = ifelse(data_pcoa$dustT == "high", rgb(153,102,51,max=255), rgb(150,150,150,max=255)))

data_pcoa_low = data_pcoa [data_pcoa$dustT == "low",] [,1:2]
data_pcoa_high = data_pcoa [data_pcoa$dustT == "high",] [,1:2]
ellipse(center = colMeans(data_pcoa_low), shape = cov(data_pcoa_low),radius = sqrt(qchisq(0.95, df=1)),
        col = rgb(102,102,102,max=255), center.cex=0, lwd = 0.2, lty = 3, fill = T, fill.alpha=0.1, pch=1)
ellipse(center = colMeans(data_pcoa_high), shape = cov(data_pcoa_high),radius = sqrt(qchisq(0.95, df=1)),
        col = rgb(153,102,51,max=255), center.cex=0, lwd = 0.2, lty = 3, fill = T, fill.alpha=0.1, pch=0)
dev.off()



#### plot based on climate cold vs. warm  ######
col_group = "Climate"
filename <- paste(input, "_" , col_group, ".pdf", sep=""); outfile <- paste(getwd(), filename, sep="/")
pdf(file = outfile, width = 4, height = 4)

plot(data_pcoa$pcoa1, data_pcoa$pcoa2, ylim=c(-0.28,0.24), xlim=c(-0.39,0.41), xlab= paste ("PCoA1 (", pcoa1_explain, "%)", sep = ""),
     ylab= paste ("PCoA2 (", pcoa2_explain, "%)", sep = ""), cex.main=0.6, cex.lab=0.6, cex.axis=0.6, cex=1.0,
     pch = 1, col = ifelse(data_pcoa$Climate == "C", rgb(0,0,255,max=255), rgb(255, 0, 0, max=255)))
data_pcoa_warm = data_pcoa [data_pcoa$Climate == "W",] [,1:2]
data_pcoa_cold = data_pcoa [data_pcoa$Climate == "C",] [,1:2]
ellipse(center = colMeans(data_pcoa_warm), shape = cov(data_pcoa_warm),radius = sqrt(qchisq(0.95, df=1)),
        col = rgb(255,0,0,max=255), center.cex=0, lwd = 0.2, lty = 3, fill = T, fill.alpha=0.1, pch=1)
ellipse(center = colMeans(data_pcoa_cold), shape = cov(data_pcoa_cold),radius = sqrt(qchisq(0.95, df=1)),
        col = rgb(0,0,255,max=255), center.cex=0, lwd = 0.2, lty = 3, fill = T, fill.alpha=0.1, pch=0)
dev.off()



#### plot based on climate epochs: Holocene vs LGS vs pre-LGS  ######
## below are climate epochs-based: [Holocene + LGS] vs pre-LGS, i.e., BLGS vs ALGS (BLGS, before LGS, i.e., Holocene + LGS; ALGS, after LGS, i.e., pre-LGS)
col_group = "stage"
filename <- paste(input, "_" , col_group, ".pdf", sep=""); outfile <- paste(getwd(), filename, sep="/")
pdf(file = outfile, width = 4, height = 4)

plot(data_pcoa$pcoa1, data_pcoa$pcoa2, ylim=c(-0.15,0.11), xlim=c(-0.13,0.22), xlab= paste ("PCoA1 (", pcoa1_explain, "%)", sep = ""),
     ylab= paste ("PCoA2 (", pcoa2_explain, "%)", sep = ""), cex.main=0.6, cex.lab=0.6, cex.axis=0.6, pch=19, cex=0.8, 
     col= ifelse(data_pcoa$stage == "Holocene", rgb(153,0,204,max=255), 
                 ifelse(data_pcoa$stage == "LGS",rgb(242,115,4,max=255), rgb(0, 153, 51, max=255))))

data_pcoa_holocene = data_pcoa [data_pcoa$stage == "Holocene",] [,1:2]
data_pcoa_LGS = data_pcoa [data_pcoa$stage == "LGS",] [,1:2]
data_pcoa_BLGS = data_pcoa [data_pcoa$stage == "BLGS",] [,1:2]
data_pcoa_ALGS = data_pcoa [data_pcoa$stage1 == "ALGS",] [,1:2]

## add ellipse for Holocene samples
# ellipse(center = colMeans(data_pcoa_holocene), shape = cov(data_pcoa_holocene),radius = sqrt(qchisq(0.95, df=1)),
#         col = rgb(153,0,204,max=255), center.cex=0, lwd = 0.2, lty = 3, fill = T, fill.alpha=0.05, pch=17)

## add ellipse for LGS samples
# ellipse(center = colMeans(data_pcoa_LGS), shape = cov(data_pcoa_LGS),radius = sqrt(qchisq(0.95, df=1)),
#         col = rgb(242,115,4,max=255), center.cex=0, lwd = 0.2, lty = 3, fill = T, fill.alpha=0.1, pch=1)

## add ellipse for BLGS samples (Holocene + LGS)
ellipse(center = colMeans(data_pcoa_BLGS), shape = cov(data_pcoa_BLGS),radius = sqrt(qchisq(0.95, df=1)),
        col = rgb(0,153,51,max=255), center.cex=0, lwd = 0.2, lty = 3, fill = T, fill.alpha=0.1, pch=0)

## add ellipse for ALGS samples (pre-LGS)
ellipse(center = colMeans(data_pcoa_ALGS), shape = cov(data_pcoa_ALGS),radius = sqrt(qchisq(0.95, df=1)),
        col = rgb(0,204,255,max=255), center.cex=0, lwd = 0.2, lty = 3, fill = T, fill.alpha=0.1, pch=1)


dev.off()

